# Generated by Django 5.1.7 on 2025-03-13 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 3, 13, 22, 44, 36, 81265), verbose_name='Опубликована'),
        ),
    ]
