# Generated by Django 5.1.7 on 2025-03-13 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 3, 13, 22, 46, 0, 157584), verbose_name='Опубликована'),
        ),
    ]
